version: '3'
services:
  web:
    build: ./src/mammapets/  # Changed build context
    container_name: application
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./src/mammapets:/app   # Map host's app code to /app in container
      - ./config:/config
    working_dir: /app          # Changed working directory
    expose:
      - "8000"
    ports:
      - "8000:8000"
    networks:
      - mammapets

  db:
    image: mysql:8.0
    container_name: data_base
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - mammapets
networks:
  mammapets: