version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: web_server
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: application
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn mammapets.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: data_base