# Generated by Django 3.0.8 on 2020-08-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateTimeField(verbose_name='date ended'),
        ),
    ]
