# Generated by Django 5.2.1 on 2025-05-24 07:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200819_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCareLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='pet_care_logs/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='web.contract')),
            ],
            options={
                'ordering': ['-date', '-timestamp'],
            },
        ),
    ]
